---
title: "XPALM INSTRUCTIONS"
output: html_document
date: '2022-08-16'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# XPalm installation

1. Install XPalm in a folder called XPalm inside the unziped folder

2. Open the shiny folder, and double-click on `Xpalm.Rproj` to open RStudio on project mode.

3. Install the XPalm R package:
   1. In RStudio, open the Packages window
   2. Click on Install
   3. "Install from:" -> choose Package Archive File
   4. Browse to the folder `XPalm_1.0.zip` and choose it (in the root folder)
4. Run the shiny app:
   1. Open the `XPalm_Shiny.R` script
   2. Click on the `Run App` button in RStudio
   
   
# run XPalm on the shiny application

1. Opne a meteo file with the browse button

2. Edit parameters in the tab 'edit parameters', otherwise let parameters value to default

3. Click on the Run XPalm button (simulation progress can be follow on the Rstudio console)

4. Visualize outputs on the 3 first tabs

5. To run a new simulation reload first the shiny app (circle arrow in the top of the app)

