// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "recomeristem_types.hpp"
#include <Rcpp.h>

using namespace Rcpp;

// getParameters_from_files
List getParameters_from_files(Rcpp::String folder);
RcppExport SEXP _recomeristem_getParameters_from_files(SEXP folderSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::String >::type folder(folderSEXP);
    rcpp_result_gen = Rcpp::wrap(getParameters_from_files(folder));
    return rcpp_result_gen;
END_RCPP
}
// getMeteo_from_files
List getMeteo_from_files(Rcpp::String folder);
RcppExport SEXP _recomeristem_getMeteo_from_files(SEXP folderSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::String >::type folder(folderSEXP);
    rcpp_result_gen = Rcpp::wrap(getMeteo_from_files(folder));
    return rcpp_result_gen;
END_RCPP
}
// init_simu
void init_simu(List dfParameters, List dfMeteo, List obs, Rcpp::String name);
RcppExport SEXP _recomeristem_init_simu(SEXP dfParametersSEXP, SEXP dfMeteoSEXP, SEXP obsSEXP, SEXP nameSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type dfParameters(dfParametersSEXP);
    Rcpp::traits::input_parameter< List >::type dfMeteo(dfMeteoSEXP);
    Rcpp::traits::input_parameter< List >::type obs(obsSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type name(nameSEXP);
    init_simu(dfParameters, dfMeteo, obs, name);
    return R_NilValue;
END_RCPP
}
// launch_simu
List launch_simu(Rcpp::String name, CharacterVector names, NumericVector params);
RcppExport SEXP _recomeristem_launch_simu(SEXP nameSEXP, SEXP namesSEXP, SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::String >::type name(nameSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type names(namesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(launch_simu(name, names, params));
    return rcpp_result_gen;
END_RCPP
}
// launch_simu_meteo
List launch_simu_meteo(Rcpp::String name, List dfMeteo);
RcppExport SEXP _recomeristem_launch_simu_meteo(SEXP nameSEXP, SEXP dfMeteoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::String >::type name(nameSEXP);
    Rcpp::traits::input_parameter< List >::type dfMeteo(dfMeteoSEXP);
    rcpp_result_gen = Rcpp::wrap(launch_simu_meteo(name, dfMeteo));
    return rcpp_result_gen;
END_RCPP
}
// get_clean_obs
List get_clean_obs(Rcpp::String vObsPath);
RcppExport SEXP _recomeristem_get_clean_obs(SEXP vObsPathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::String >::type vObsPath(vObsPathSEXP);
    rcpp_result_gen = Rcpp::wrap(get_clean_obs(vObsPath));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_run_from_dataframe
List rcpp_run_from_dataframe(List dfParameters, List dfMeteo);
RcppExport SEXP _recomeristem_rcpp_run_from_dataframe(SEXP dfParametersSEXP, SEXP dfMeteoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type dfParameters(dfParametersSEXP);
    Rcpp::traits::input_parameter< List >::type dfMeteo(dfMeteoSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_run_from_dataframe(dfParameters, dfMeteo));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_get_vObs
List rcpp_get_vObs(Rcpp::String vObsPath);
RcppExport SEXP _recomeristem_rcpp_get_vObs(SEXP vObsPathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::String >::type vObsPath(vObsPathSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_get_vObs(vObsPath));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_reduceVobs
List rcpp_reduceVobs(List vObs, List results);
RcppExport SEXP _recomeristem_rcpp_reduceVobs(SEXP vObsSEXP, SEXP resultsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type vObs(vObsSEXP);
    Rcpp::traits::input_parameter< List >::type results(resultsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_reduceVobs(vObs, results));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_reduceResults
List rcpp_reduceResults(List results, List vobs);
RcppExport SEXP _recomeristem_rcpp_reduceResults(SEXP resultsSEXP, SEXP vobsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type results(resultsSEXP);
    Rcpp::traits::input_parameter< List >::type vobs(vobsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_reduceResults(results, vobs));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_recomeristem_getParameters_from_files", (DL_FUNC) &_recomeristem_getParameters_from_files, 1},
    {"_recomeristem_getMeteo_from_files", (DL_FUNC) &_recomeristem_getMeteo_from_files, 1},
    {"_recomeristem_init_simu", (DL_FUNC) &_recomeristem_init_simu, 4},
    {"_recomeristem_launch_simu", (DL_FUNC) &_recomeristem_launch_simu, 3},
    {"_recomeristem_launch_simu_meteo", (DL_FUNC) &_recomeristem_launch_simu_meteo, 2},
    {"_recomeristem_get_clean_obs", (DL_FUNC) &_recomeristem_get_clean_obs, 1},
    {"_recomeristem_rcpp_run_from_dataframe", (DL_FUNC) &_recomeristem_rcpp_run_from_dataframe, 2},
    {"_recomeristem_rcpp_get_vObs", (DL_FUNC) &_recomeristem_rcpp_get_vObs, 1},
    {"_recomeristem_rcpp_reduceVobs", (DL_FUNC) &_recomeristem_rcpp_reduceVobs, 2},
    {"_recomeristem_rcpp_reduceResults", (DL_FUNC) &_recomeristem_rcpp_reduceResults, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_recomeristem(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
