# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

runFolder <- function(folder) {
    .Call(`_XPalm_runFolder`, folder)
}

runDF <- function(dfParameters, dfMeteo) {
    .Call(`_XPalm_runDF`, dfParameters, dfMeteo)
}

getValues <- function() {
    .Call(`_XPalm_getValues`)
}

getHeaders <- function() {
    .Call(`_XPalm_getHeaders`)
}

