# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getParameters_from_files <- function(folder) {
    .Call('_recomeristem_getParameters_from_files', PACKAGE = 'recomeristem', folder)
}

getMeteo_from_files <- function(folder) {
    .Call('_recomeristem_getMeteo_from_files', PACKAGE = 'recomeristem', folder)
}

init_simu <- function(dfParameters, dfMeteo, obs, name) {
    invisible(.Call('_recomeristem_init_simu', PACKAGE = 'recomeristem', dfParameters, dfMeteo, obs, name))
}

launch_simu <- function(name, names = character(), params = numeric()) {
    .Call('_recomeristem_launch_simu', PACKAGE = 'recomeristem', name, names, params)
}

launch_simu_meteo <- function(name, dfMeteo) {
    .Call('_recomeristem_launch_simu_meteo', PACKAGE = 'recomeristem', name, dfMeteo)
}

get_clean_obs <- function(vObsPath) {
    .Call('_recomeristem_get_clean_obs', PACKAGE = 'recomeristem', vObsPath)
}

rcpp_run_from_dataframe <- function(dfParameters, dfMeteo) {
    .Call('_recomeristem_rcpp_run_from_dataframe', PACKAGE = 'recomeristem', dfParameters, dfMeteo)
}

rcpp_get_vObs <- function(vObsPath) {
    .Call('_recomeristem_rcpp_get_vObs', PACKAGE = 'recomeristem', vObsPath)
}

rcpp_reduceVobs <- function(vObs, results) {
    .Call('_recomeristem_rcpp_reduceVobs', PACKAGE = 'recomeristem', vObs, results)
}

rcpp_reduceResults <- function(results, vobs) {
    .Call('_recomeristem_rcpp_reduceResults', PACKAGE = 'recomeristem', results, vobs)
}

