---
title: "Report_Visu_debug_XPalm"
author: "Raphaël PEREZ"
date: "14/04/2020"
output:
  html_document:
    df_print: paged
  pdf_document: default
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F,warning = F,message =  F)
```


```{r generate Xplam param, echo = F,warning = F,message =  F}
###script to test and visualize outputs of Xpalm###
##R PEREZ, April 2020


# Load packages -----------------------------------------------------------

packs <- c("lubridate", "stringr", "ggplot2",'dplyr','viridis','tidyr','data.table','plotly','xtable')
InstIfNec<-function (pack) {
  if (!do.call(require,as.list(pack))) {
    do.call(install.packages,as.list(pack))  }
  do.call(require,as.list(pack)) }
lapply(packs, InstIfNec)


# theme -------------------------------------------------------------------

myTheme <- theme(
  panel.background=element_rect(fill="transparent", color=NA),  
  plot.background = element_rect(fill = "transparent",colour = NA),
  axis.line=element_line(colour="black"), 
  axis.title=element_text(size=16),
  axis.text.y=element_text(size=14, colour="black"), 
  axis.text.x=element_text(size=14, colour="black", angle=0, hjust=0.5),
  panel.grid.minor = element_blank(), 
  panel.grid.major = element_line(colour="grey90", size=0.2), 
  legend.position="bottom", 
  legend.text=element_text(size=14),
  legend.title=element_text(size=14)
)



# load functions ----------------------------------------------------------

source('generate_params.R')
source('generate_meteo.R')


# generate param and meteo files ------------------------------------------

age_ini=3
seed=1

generate_param(dir='../parameters/',filename = 'XPalm_parameters',AGE_INI = age_ini,SEED = seed)

meteo_file="meteo_sub_SMSE"
generate_meteo(dir_raw = '../parameters/',filename = meteo_file,date_ini = NULL,date_end = NULL)


# lunch simu --------------------------------------------------------------
###externally

sim_name=paste0('Simu_',meteo_file,'_age',age_ini,'_seed',seed)
```


```{r lunch Xplam simu}

list_simu=str_remove(string = list.files(path = '../Simu/',pattern = '.RData'),pattern = '.RData')

if (sim_name %in% list_simu){
  cat('Simulation already lunched')
}else{cat('Simulation not yet lunched --> lunch in QT')}

```


```{r load}
# load outputs ------------------------------------------------------------

if (!(sim_name %in% list_simu)){
  don=data.table::fread(file =paste0('../../bin/msvc14/x64/results.csv'),header=T)%>%
  mutate(Date=ymd(Date),
         Age=(Date-first(Date))/365)
save(x=don,file =paste0('../Simu/',sim_name,'.RData'))
}



# load outputs ------------------------------------------------------------

load(paste0('../Simu/',sim_name,'.RData'))


vars=don%>%
  select(-c(Date,Age,TREE_AGE))%>%
  colnames()


tableVar=data.frame(var=vars,min=0,max=NA,type='sink & source')
levels(tableVar$type)=c('sink & source','meteo','prod')
tableVar[tableVar$var %in% c('EI','FRACTION_NON_STR_BIOMASS_TOTAL','FR_FRUITS','FR_RESTE','FTSW'),]$max=1
tableVar[tableVar$var %in% c('C_BALANCE'),]$max=0
tableVar[tableVar$var %in% c('FRACTION_NON_STR_BIOMASS_TOTAL'),]$min=1

tableVar[tableVar$var %in% c("FTSW","RG","RAIN","TEFF"),]$type='meteo'
tableVar[tableVar$var %in% c("PLANTLEAFAREA",'LAI',"PHYTOMERNUMBER","NEWPHYTOMEREMERGENCE","LEAVES_NON_STRUCTURAL_BIOMASS_HARVESTED","LEAVES_STRUCTURAL_BIOMASS_HARVESTED","MALE_BIOMASS_HARVESTED","PEDUNCLE_BIOMASS_HARVESTED","BUNCH_NONOIL_BIOMASS_HARVESTED","BUNCH_OIL_BIOMASS_HARVESTED","TRUNK_BIOMASS","TRUNK_HEIGHT"),]$type='prod'



# generate outputs ------------------------------------------------------------

don2=don%>%
  tidyr::gather(key = 'var',value='value',-c(Date,Age,TREE_AGE))

don2=merge(don2,tableVar)%>%
  mutate(outliers=ifelse((!is.na(value) & value<min) |(!is.na(value) & !is.na(max) & value>max),'yes','no'))


out=don2%>%
  mutate(simu=sim_name)%>%
  filter(outliers=='yes')
```



```{r visu}
# save outputs ------------------------------------------------------------

pdf(paste0('../Outputs/',sim_name,'.pdf'),onefile = T)
for (v in vars){
  sub=don2%>%
    filter(var==v)
  
  gr=ggplot()+
    geom_hline(data = sub,aes(yintercept = min),lty=2)+
    geom_hline(data = sub,aes(yintercept = max),lty=2)+
    geom_path(data=sub,aes(x=Date,y=value))+
    geom_point(data=sub[sub$outliers=='yes',],aes(y=value,x=Date),col=2)+
    ylab(v)+
    myTheme
  
  print(gr)
}
dev.off()


pdf(paste0('../Outputs/Prod_',sim_name,'.pdf'),onefile = T)

YEARS=unlist(don%>%
mutate(year=year(Date),month=month(Date))%>%
  group_by(year)%>%
  summarize(count=n_distinct(month))%>%
  filter(count==12)%>%
  ungroup()%>%
  select(year)%>%
  unique())

  sub=don%>%
  mutate(year=year(x = Date))%>%
    filter(year %in% YEARS)%>%
    mutate(FFB=BUNCH_NONOIL_BIOMASS_HARVESTED+BUNCH_OIL_BIOMASS_HARVESTED)%>%
    group_by(year)%>%
    summarize(tree_age=mean(TREE_AGE)/365,
      FFB=sum(FFB)*143/(10**6),
              OIL=sum(BUNCH_OIL_BIOMASS_HARVESTED)*143/(10**6))%>%
    ungroup()%>%
    select(tree_age,year,FFB,OIL)%>%
    tidyr::gather(key = 'var',value='value',-c(tree_age,year))
    
    
  
  gr=ggplot(data=sub,aes(x=tree_age,y=value))+
    geom_path()+
    geom_point()+
    ylab('production (tonnes.ha-1.year-1)')+
    facet_grid(~var)+
    xlab('plant age')+
    myTheme
  
  print(gr)

dev.off()

```




```{r plotly_visu}
for (t in unique(don2$type)){
  sub=don2%>%
    filter(type==t)
  
  gr=ggplot()+
    geom_hline(data = sub,aes(yintercept = min),lty=2)+
    geom_hline(data = sub,aes(yintercept = max),lty=2)+
    geom_path(data=sub,aes(x=Date,y=value))+
    geom_point(data=sub[sub$outliers=='yes',],aes(y=value,x=Date),col=2)+
    facet_wrap(~var,scales = 'free_y')+
    myTheme
  
  print(ggplotly(gr))
}


if(nrow(out)>0){
  
  print(out)
  
}

```

